# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(db_index=True)),
                ('b', models.IntegerField(db_index=True)),
                ('divisor', models.IntegerField()),
            ],
        ),
    ]
